baseURL = "https://frosklis.tk/"
languageCode = "es-es"
title = "Claudio Noguera"
theme = "diary"
GoogleAnalytics = "UA-267152-14"
newContentEditor = "code"

[params]
  author = "Claudio Noguera"
  description = "Sitio web de Claudio Noguera"
  favicon = "/favicon.png"
