baseURL = "https://frosklis.tk/"
languageCode = "es-es"
title = "Claudio Noguera"
theme = "scratch"
GoogleAnalytics = "UA-267152-14"
newContentEditor = "nvim"
disqus = "frosklis"

[params]
  author = "Claudio Noguera"
  description = "Sitio web de Claudio Noguera"
  favicon = "/favicon.png"
  logo = "/claudio_salinas.jpg"
  github = "frosklis"
  linkedin = "claudionoguera"
  twitter = "claudio1985"
  goodreads = "claudio85"
  # email = "claudio.noguera@gmail.com"


# https://blog.atj.me/2017/10/generate-yearly-and-monthly-archive-pages-with-hugo-sections/
# prevent hugo from creating folders/indexes for each section
disableKinds = ["section"]

[permalinks]
  # :title is used if :slug is not defined in post frontmatter
  posts = "/:year/:month/:slug/"
  archm = "/:year/:month/"
  archy = "/:year/"

[markup]
  # defaultMarkdownHandler = "goldmark"
  defaultMarkdownHandler = "blackfriday"
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = true
